fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib
    powershell:  https://github.com/puppetlabs/puppetlabs-powershell
    win_facts:  https://github.com/liamjbennett/puppet-win_facts
    download_file: https://github.com/voxpupuli/puppet-download_file
  symlinks:
    dotnet: "#{source_dir}"
