fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib
    powershell:  https://github.com/puppetlabs/puppetlabs-powershell
    remote_file: https://github.com/lwf/puppet-remote_file
  symlinks:
    dotnet: "#{source_dir}"
